# Generated by Django 4.2.15 on 2026-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image_key",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_key",
        ),
        migrations.AddField(
            model_name="category",
            name="image_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="image_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
