# Generated by Django 4.2.15 on 2026-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_remove_category_image_key_remove_product_image_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
