# Generated by Django 4.2.15 on 2026-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_remove_company_logo_company_logo_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="logo_key",
        ),
        migrations.AddField(
            model_name="company",
            name="logo_keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
