# Generated by Django 4.2.15 on 2026-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero_carousel", "0002_remove_carouselslide_image_carouselslide_image_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carouselslide",
            name="image_key",
        ),
        migrations.AddField(
            model_name="carouselslide",
            name="image_keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
