# Generated by Django 4.2.15 on 2026-05-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero_carousel", "0003_remove_carouselslide_image_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselslide",
            name="dimensions",
            field=models.CharField(
                blank=True, help_text="e.g., 1920x1080", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="carouselslide",
            name="display_on",
            field=models.CharField(
                choices=[
                    ("desktop", "Desktop Only"),
                    ("mobile", "Mobile Only"),
                    ("both", "Both"),
                ],
                default="both",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="carouselslide",
            name="mobile_dimensions",
            field=models.CharField(
                blank=True, help_text="e.g., 1080x1920", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="carouselslide",
            name="mobile_image_keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
