# Generated by Django 4.2.15 on 2026-04-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_remove_company_logo_key_company_logo_keys"),
        ("sanitary", "0004_remove_sanitaryproduct_image_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanitaryproduct",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sanitary_products",
                to="companies.company",
            ),
        ),
    ]
