# Generated by Django 4.2.15 on 2026-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_collections", "0002_remove_productcollection_cover_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcollection",
            name="image_key",
        ),
        migrations.AddField(
            model_name="productcollection",
            name="image_keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
